### ISSUE TITLE
Operator is unable to find the S3 bucket

### ISSUE THREAD

**Issue by JohnMops** [aws/aws-service-operator-k8s#10]
**Describe the bug**
After creating the aws operator using the aws-service-operator.yaml and isnerting the correct flags,
the logs show that there is no such bucket.

**Steps to reproduce**

1. Download aws-service-operator.yaml from the AWS page
2. Insert args:
    - args:
        - server
        - --cluster-name= <NAME>
        - --region=<REGION>
        - --account-id=<ID>
        - --bucket=<BUCKET NAME>
        - --loglevel=Debug
3. kubectl apply -f aws-service-operator -n <namespace>
4. kubectl -f apply <elasticache.yaml>

**Expected outcome**
The above will create the cdfn's and the namespace 
Afterwords it will create an elasticache service that will send an API request to Cloudformation 
to create a stack that will create a Redis cluster

**Environment**

* Kubernetes version:

Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-18T14:56:51Z", GoVersion:"go1.12.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.12-eks-c500e1", GitCommit:"c500e11584c323151d6ab17526d1ed7461e45b0c", GitTreeState:"clean", BuildDate:"2019-10-22T03:11:52Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}

* Using EKS (yes), if so version? :

eks.6

* AWS service targeted (S3, RDS, etc.):

Cloudformation/S3/Redis

*Logs from the aws-service-operator deploy:

time="2019-12-02T13:50:02Z" level=error msg="error creating elasticache 'jenkins-integ-test-20191202014223'" error="ValidationError: S3 error: The specified bucket does not exist\nFor more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html\n\tstatus code: 400, request id: c5406494-b8a3-4043-ab7f-eed653e99a20" hostname=aws-service-operator-5459ffd49b-pw9m5

**Comment by mhausenblas** [comment]
@JohnMops thanks for raising the issue and sorry for the delay following up here. It seems that you're asking about a problem with the (deprecated) [aws-service-operator](https://github.com/amazon-archives/aws-service-operator) project? This project here doesn't (yet) have code, we're in the [design phase](https://github.com/aws/aws-service-operator-k8s/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Adesign).
