### ISSUE TITLE
determine primary API namespace

### ISSUE THREAD

**Issue by jaypipes** [aws/aws-service-operator-k8s#23]
We should decide what the primary API namespace for the CRDs exposed by AWS Service Operator.

The original ASO used the namespace `service-operator.aws` for its CRDs:

https://github.com/amazon-archives/aws-service-operator/blob/b4befd62322a57ac78aa39ea08771fc32912592a/configs/aws-service-operator.yaml#L37

Other Kubernetes controllers that deal with AWS resources use different namespaces:

* ALB Ingress controller v2 uses `k8s.aws`: https://github.com/kubernetes-sigs/aws-alb-ingress-controller/blob/v2/config/crds/ingress_v1alpha1_loadbalancer.yaml#L7
* AppMesh controller for k8s uses `k8s.aws`: https://github.com/aws/aws-app-mesh-controller-for-k8s/blob/dbfce09bf701846fb7cacd8e57c424191334505b/deploy/all.yaml#L7
* ENIConfig from CNI plugin v1 uses `k8s.amazonaws.com`: https://github.com/aws/amazon-vpc-cni-k8s/blob/73d031441c8b20e73675fc26cd16bf016702152a/pkg/eniconfig/eniconfig.go#L152
* Sagemaker controller for k8s used `aws.amazon.com`: https://github.com/aws/amazon-sagemaker-operator-for-k8s/blob/1e4bee1f0b172ab83385d1aa113b22f065baf1c7/config/crd/bases/sagemaker.aws.amazon.com_models.yaml#L16

We should standardize on one namespace.

**Comment by jaypipes** [comment]
My proposal would be to use `services.k8s.aws` as the top-level domain namespace and then for each service exposed in ASO, use the AWS service's nickname/shortname, so something like this:

- `elbv2.services.k8s.aws`
- `ec2.services.k8s.aws`
- `s3.services.k8s.aws`

**Comment by mhausenblas** [comment]
+1 to this proposal @jaypipes, let's lock it down and make it happen. I'm happy to close this issue with the decision to  use `services.k8s.aws`.

**Comment by M00nF1sh** [comment]
+1 🤣

**Comment by daviddyball** [comment]
I actually think `amazonaws.com` would be best... the `kiam` and `kube2iam` controllers already use `iam.amazonaws.com` annotations, so it's not much of a change to have:
* `ec2.amazonaws.com`
* `rds.amazonaws.com`
* `s3.amazonaws.com`

**Comment by mhausenblas** [comment]
@daviddyball thing is, we (as in our service team) don't own `amazonaws.com` but we *can* own others, hence making dereferenceable URLs for docs possible.

**Comment by daviddyball** [comment]
@mhausenblas Do you own `aws.` root domain? `services.k8s.aws.` might have the same issue no?

**Comment by mhausenblas** [comment]
I do not own `aws`, no. But, you know, like "the power of subdomains and delegation" ;)

**Comment by jaypipes** [comment]
Closing this issue. We'll be using `services.k8s.aws`
