### ISSUE TITLE
Determine service support for tag-on-create

### ISSUE THREAD

**Issue by jaypipes** [aws/aws-service-operator-k8s#29]
Determine which services support tag-on-create semantics and for which resources in those services. If we are able to use tag-on-create, we might be able to use tag-based authz to limit the blast radius of the IAM role under which the controller's pod service account executes.

**Comment by mhausenblas** [comment]
To confirm, we're talking about [Controlling Access to and for IAM Users and Roles Using IAM Resource Tags](https://docs.aws.amazon.com/IAM/latest/UserGuide/access_iam-tags.html).

**Comment by mhausenblas** [comment]
So, ARG lists [Supported Resources](https://docs.aws.amazon.com/ARG/latest/userguide/supported-resources.html) albeit without tag-on-create differentiation.

**Comment by goraxe** [comment]
cool, came here from the giant thread over at https://github.com/aws/containers-roadmap/issues/456 to say more or less this.  I have been looking at tag based policy set for a while via the ABAC style roles.  One hickup for us is that dynamodb does not support this currently.  This is the list I had been looking at -> https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_aws-services-that-work-with-iam.html#database_svcs

**Comment by mhausenblas** [comment]
Conclusion: not feasible.
