### ISSUE TITLE
Support for creating Network Services

### ISSUE THREAD

**Issue by seizadi** [aws/aws-service-operator-k8s#30]
**Is your feature request related to a problem?**
We plan to use AWS Operator for provisioning Applications that need network resources, things like
VPCs, Internet Gateway, Subnets

**Describe the solution you'd like**
The current CRD/Cloud Formation pattern is fine for creating these and two patterns for consuming these would be the ConfigMap or API query of resource Status, the later preferred since a higher level Operator will drive the overall flow and resolve state.

**Describe alternatives you've considered**
Fork current AWS Operator project or write a new operator for this feature.

**Comment by seizadi** [comment]
I forked the repo and added vpc support to get some experience with the project: https://github.com/seizadi/aws-service-operator

You can very easily change the Cloud Formation but since the models are compiled we need some constructs to enable using the same schema to represent a range of properties that can be input and output from in the model for networking/vpc use cases.

Here are some concrete patterns that would be helpful for vpc creation:

- Specify number of subnets, they can specified with fixed CIDRs from external IPAM 
- Specify top vpc CIDR  have the CloudFormation compute subnets CIDRs based on template user specifies 
e.g. CidrBlock: !Select [ 3, !Cidr [ !Ref VpcCIDR, !Ref VpcCIDR, !Ref Subnet1Count,  !Ref Subnet1Bits]]

The other pattern would be helpful to pass arguments in list for things like:
- AZ list e.g. 
          AvailabilityZone: !Select
            - !Select [ "0", !Ref AzIndexList ]
            - Fn::GetAZs: !Ref 'AWS::Region'

We distribute subnets evenly with AZs for HA but maybe others have other patterns to map AZs to Subnets.

List for Peering in Routes:
-      RedisPeerProperties:
        Type: CommaDelimitedList
        Description: "Redis peering connection properties in the format: {RedisCIDR},{RedisVpcId},{RedisRegion},{RedisAccountId}"
        Properties:
          PeerVpcId: !Select ["1", !Ref RedisPeerProperties]
          PeerRegion: !Select ["2", !Ref RedisPeerProperties]
          PeerOwnerId: !Select ["3", !Ref RedisPeerProperties]
          PeerRoleArn: !FindInMap [EnvMap, !Ref Env, PeeringRole]

IP list that would be used in SG to provide ACL, e.g.
     BastionSG:
        Type: AWS::EC2::SecurityGroup
        Properties:
          GroupDescription: SSH access to VPC from External Site
          VpcId: !Ref Vpc
          SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: 22
              ToPort: 22
              CidrIp: !Select ["1", !Ref ExternalSiteProperties]
              Description: External Site1

**Comment by mhausenblas** [comment]
Closing since you're referring to the old (archived) project. This here is a new project that is in the design phase and doesn't as of yet has any code.
