### ISSUE TITLE
Better error logging for case of Cloud Formation errors.

### ISSUE THREAD

**Issue by seizadi** [aws/aws-service-operator-k8s#31]
**Describe the bug**
When I get k8s error log the cloud formation error seems to be truncated

**Steps to reproduce**
Cause an error and match the error displayed in k8s log with what you see in aws console for CloudFormation.

**Expected outcome**
The two logs should have the same information.

**Environment**
k8s 1.17

**Comment by mhausenblas** [comment]
Closing since you're referring to the old (archived) project. This here is a new project that is in the design phase and doesn't as of yet has any code.
