### ISSUE TITLE
Support IRSA for the service operator role assumption

### ISSUE THREAD

**Issue by jessebye** [aws/aws-service-operator-k8s#8]
**Is your feature request related to a problem?**
The old version of this operator did not natively support using [IAM Roles for Service Accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) to assume the role necessary to provision resources.

**Describe the solution you'd like**
I think all that needs to happen is that the service operator server gets built with a compatible version of the `aws-sdk-go`, i.e. version `1.23.13` or later. Then, a method for adding the proper annotation to the `ServiceAccount` resource in the manifests needs to be provided.

**Comment by mhausenblas** [comment]
Thanks and IRSA support is covered in #3.
